[package]
name = "leetcode"
version = "0.1.0"
edition = "2021"
# default-run = "1765K"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"

[features]
# local = []


[profile.release]
debug = true
